Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-TASCAM_US-1x2HR_no_serial_number-00.analog-stereo"
LastUsedOutput = ""
