add_newline = false

[cmd_duration]
disabled = true

[directory]
format = '\[[$path]($style)\][$read_only]($read_only_style) '

[git_branch]
format = '[$symbol$branch]($style) '

[hostname]
format = '@[$hostname]($style) '

[line_break]
disabled = true

[nodejs]
disabled = true

[username]
format = '[$user]($style)'

